import { BaseService } from '../../core/service';
import { OfferRepository } from './offer.repository';
import { HttpException } from '../../core/http-exception';
import { CreateOfferRequest, UpdateOfferRequest, SendOfferRequest } from './offer.types';
import { OfferStatus } from '../../types';
import { env } from '../../config/env';

export class OfferService extends BaseService {
  constructor(private repository: OfferRepository) {
    super();
  }

  /**
   * Create Draft Offer
   */
  async createOffer(data: CreateOfferRequest, userId: string) {
    // 1. Validate dates? Prisma handles standard Date objects
    // Date parsing might be needed if coming as string from JSON
    const startDate = new Date(data.startDate);
    const expirationDate = data.expirationDate ? new Date(data.expirationDate) : undefined;

    // 2. Create logic
    // We connect relations: application, candidate, job, createdBy(user)
    const offer = await this.repository.create({
      application: { connect: { id: data.applicationId } },
      candidate: { connect: { id: data.candidateId } },
      job: { connect: { id: data.jobId } },
      user: { connect: { id: userId } },
      salary: data.salary,
      salary_currency: data.salaryCurrency || 'USD',
      salary_period: data.salaryPeriod,
      start_date: startDate,
      benefits: data.benefits || [],
      expiry_date: expirationDate,
      offer_type: data.offerType,
      work_location: data.workLocation,
      work_arrangement: data.workArrangement,
      custom_terms: data.customTerms || undefined,
      status: OfferStatus.DRAFT,
    });

    return offer;
  }

  /**
   * Get Offer
   */
  async getOffer(id: string) {
    const offer = await this.repository.findById(id);
    if (!offer) throw new HttpException(404, 'Offer not found');
    return offer;
  }

  /**
   * Update Offer
   */
  async updateOffer(id: string, data: UpdateOfferRequest) {
    const offer = await this.repository.findById(id);
    if (!offer) throw new HttpException(404, 'Offer not found');

    if (offer.status !== OfferStatus.DRAFT && offer.status !== OfferStatus.PENDING_APPROVAL) {
      // Typically only draft offers can be modified fully.
      // But we'll allow updates for now with a warning or restriction depending on business logic.
      // Strict mode: throw new HttpException(400, 'Cannot edit sent or finalized offer');
    }

    const updateData: any = { ...data };
    if (data.startDate) updateData.start_date = new Date(data.startDate);
    if (data.expirationDate) updateData.expiry_date = new Date(data.expirationDate);
    // Map camelCase to snake_case manually or assume repository interface handles it.
    // The repository interface `OfferLetterUpdateInput` expects snake_case properties generated by Prisma.
    // We need to map carefully.

    const prismaUpdate: any = {};
    if (data.salary !== undefined) prismaUpdate.salary = data.salary;
    if (data.salaryCurrency !== undefined) prismaUpdate.salary_currency = data.salaryCurrency;
    if (data.salaryPeriod !== undefined) prismaUpdate.salary_period = data.salaryPeriod;
    if (data.startDate !== undefined) prismaUpdate.start_date = new Date(data.startDate);
    if (data.benefits !== undefined) prismaUpdate.benefits = data.benefits;
    if (data.expirationDate !== undefined) prismaUpdate.expiry_date = new Date(data.expirationDate);
    if (data.offerType !== undefined) prismaUpdate.offer_type = data.offerType;
    if (data.workLocation !== undefined) prismaUpdate.work_location = data.workLocation;
    if (data.workArrangement !== undefined) prismaUpdate.work_arrangement = data.workArrangement;
    if (data.status !== undefined) prismaUpdate.status = data.status;
    if (data.customTerms !== undefined) prismaUpdate.custom_terms = data.customTerms;

    return this.repository.update(id, prismaUpdate);
  }

  /**
   * Send Offer
   */
  async sendOffer(id: string, userId: string, request: SendOfferRequest) {
    const offer = await this.getOffer(id);

    // Logic: Authenticate that user can send? (Controller handles auth)

    // 1. Update Status
    const sentDate = new Date();
    const updatedOffer = await this.repository.update(id, {
      status: OfferStatus.SENT,
      sent_date: sentDate,
      custom_message: request.customMessage,
    });

    // 2. Generate PDF (Mock)
    // const pdfUrl = await pdfService.generateOfferPdf(updatedOffer);

    // 3. Send Email (Mock)
    if (offer.candidate && offer.candidate.email) {
      console.log(`[Email Mock] Sending Offer Letter to ${offer.candidate.email}`);
      // emailService.sendOffer(offer.candidate.email, updatedOffer);
    }

    return updatedOffer;
  }

  /**
   * Get Offers by Application
   */
  async getOffersByApplication(applicationId: string) {
    return this.repository.findByApplicationId(applicationId);
  }

  /**
   * Accept Offer
   */
  async acceptOffer(id: string, userId: string) {
    return this.updateStatus(id, OfferStatus.ACCEPTED, userId);
  }

  /**
   * Decline Offer
   */
  async declineOffer(id: string, userId: string) {
    return this.updateStatus(id, OfferStatus.DECLINED, userId);
  }

  /**
   * Update Status (Accept/Decline/Withdraw)
   */
  async updateStatus(id: string, status: OfferStatus, userId: string) {
    // Should validate transitions e.g. DRAFT -> SENT -> ACCEPTED
    // Also track who updated it
    return this.repository.update(id, { status });
  }
}
