-- AlterEnum
ALTER TYPE "HiringMode" ADD VALUE 'ASSESSMENT_ONLY';

-- AlterEnum
ALTER TYPE "VirtualTransactionType" ADD VALUE 'ASSESSMENT_CREDIT_DEDUCTION';
ALTER TYPE "VirtualTransactionType" ADD VALUE 'ASSESSMENT_CREDIT_REFUND';
